### PR TITLE
added login and registration

### PR DESCRIPTION
**Pull request by rezarex**

### CODE REVIEW

**Comment by rezarex** [comment]
I added a basic login/registration, normal users can register and login, the admin can edit the user's permissions, only admins can login via the django admin page, users can only access the homepage if they are registered/ logged in. This is a basic setup.

**Comment by rezarex** [comment]
Hi, I had installed django crispy forms library, please use either:
pip install django-crispy-forms
or
conda install django-crispy-forms

**Comment by ManofWax** [comment]
Ok by adding `django-crispy-forms` e `crispy-bootstrap5` it works. Can you please add both in `requirements.txt`?

Can you also change this two issues on the interface:
The `Welcome user_name` should not be placed there. I think we can remove it for now:
image

The login and register forms takes all the width of the browser:
image

It's better to limit it to a fixed amount like 800/900px. Also there is an error on the register button (`Register/button>`)

**Comment by rezarex** [comment]
Hi @ManofWax , sorry, my laptop crashed and I had to get a new one. Just finished setting up. Will be submitting the changes by midday tomorrow.

**Pull request closed without merging**
