### PR TITLE
Build Dashboard + Landing Page + Hook in APIs

### PR DESCRIPTION
**Pull request by abheektripathy**
opening up a pr so to track my commits.
not ready for a merge yet.

### CODE REVIEW

**Comment by abheektripathy** [comment]
i have wrapped up the dashboard's ui, plus hooked in the drf api's to make it functional.
the pr's ready for a review now.

**Comment by ManofWax** [comment]
I notice two issue in the login form:
image

The `username` label should be changed in `email` and the password field should not be visible. Also an error should be shown when the authentication fails. (IE: "Wrong username or password").

The dashboards looks good do you think making the world map zoomable will be feasable?

**Comment by abheektripathy** [comment]
fixing this right now,  plus adding notifications here.

p.s for the world map, let me try to implement that, would update you.

**Comment by abheektripathy** [comment]
hey @ManofWax fixed the issues up, plus the world map's now zoomable.
Screenshot 2023-08-10 at 3 44 11 PM

**Comment by abheektripathy** [comment]
fixed up the marker issue as well.
https://github.com/certego/BuffaLogs/assets/90976669/b55695ac-c35b-43cd-ad9f-9e219f34c3c9

**Review by ManofWax — APPROVED** [review]

**Pull request merged**
